# Generated by Django 5.0.3 on 2024-10-15 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('Customer_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=20)),
                ('address', models.CharField(blank=True, default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Order_date', models.DateTimeField()),
                ('Total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold.customers')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold.products')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold.customers')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold.orders')),
            ],
        ),
    ]
