# Generated by Django 5.0.3 on 2024-10-15 07:57

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0003_customers_groups_customers_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customers',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, unique=True),
        ),
    ]
