# Generated by Django 5.0.3 on 2024-10-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0004_alter_customers_managers_alter_customers_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customers',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
    ]
