# Generated by Django 5.0.3 on 2024-10-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0005_alter_customers_managers_alter_customers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default=None, upload_to='products'),
            preserve_default=False,
        ),
    ]
