# Generated by Django 5.0.3 on 2024-10-16 21:05

import gold.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0006_products_product_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customers',
            managers=[
                ('objects', gold.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customers',
            name='Customer_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
