# Generated by Django 5.0.3 on 2024-10-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0009_alter_products_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
