# Generated by Django 5.0.3 on 2024-10-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0011_cart_alter_products_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Cart_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
