# Generated by Django 5.0.3 on 2024-10-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0015_alter_cart_cart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Cart_description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Cart_image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Cart_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Cart_price',
        ),
    ]
