# Generated by Django 5.0.3 on 2024-10-21 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0016_remove_cart_cart_description_remove_cart_cart_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gold.products', unique=True),
        ),
    ]
