# Generated by Django 5.0.3 on 2024-10-30 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0022_alter_cart_cart_id_alter_cart_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Cart_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='Product_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='gold.products'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False, unique=True),
        ),
    ]
