# Generated by Django 5.0.3 on 2024-10-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0023_remove_cart_cart_id_cart_product_id_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Product_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='Cart_description',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='Cart_image',
            field=models.ImageField(default=None, upload_to='cart/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='Cart_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='Cart_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
