# Generated by Django 5.0.3 on 2024-10-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0025_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Product_id',
            field=models.IntegerField(default=None),
        ),
    ]
