# Generated by Django 5.0.3 on 2024-11-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0026_cart_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Cart_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
