# Generated by Django 5.0.3 on 2024-11-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0029_products_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_category',
        ),
        migrations.AddField(
            model_name='products',
            name='product_cartegory',
            field=models.CharField(default='breakfast', max_length=255),
        ),
    ]
