# Generated by Django 5.0.3 on 2024-11-17 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0031_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Cart_amount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Cart_description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Cart_image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Cart_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Cart_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Product_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='gold.products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
