# Generated by Django 5.0.3 on 2024-11-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0033_rename_customer_id_orders_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
