# Generated by Django 5.0.3 on 2024-12-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0034_alter_orders_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('image', models.ImageField(upload_to='media/gallery')),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
