# Generated by Django 5.0.3 on 2024-12-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0035_gallery_delete_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
