# Generated by Django 5.0.3 on 2024-12-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0038_customers_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
